config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :games do
    post "up"
    post "down"
  end

  resources :tags
  resources :comments do
    post "up"
    post "down"
  end

  resources :users do
    resources :relationships
    get "add_game_to_user_new"
    post "add_game_to_user_create"
  end

  resources :libraries

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'games#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  has_many :libraries
  has_many :games, through: :libraries
  has_many :comments
  has_many :friends, through: :relationships, source: :friend
  has_many :relationships, foreign_key: :user_id, class_name: "Relationship"
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  	@relationships = Relationship.all
  	@relationship = Relationship.new
  	if user_signed_in?
  		@user = current_user
  	end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/add_game_to_user_new.html.erb
add new game to library here
<div>
  <!-- new game search container -->
  <div>
    <!-- search bar container -->
    <div>
      <!-- search bar goes here -->
    </div>
  </div>
  <div>
    <!-- game list container -->
    <div>
      <!-- each game list goes here -->
    </div>
  </div>
  <div>
    <!-- button container -->
    <div>
      <!-- cancel -->
    </div>
    <div>
      <!-- add -->
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="relation_container">
  <div class="relationship_container">
      <h1>All Users</h1>
      <div class="content_list">
        <ul>
        	<% @users.each do |user| %>
        		<li> <%= link_to user.username, user_path(user) %>

        		<% if user_signed_in? && !@user.friends.include?(user) && @user != user %>
        			<%= form_for(@relationship, url: user_relationships_path(@user)) do |f| %>
        				<%= f.hidden_field :friend_id, :value => user.id %>
        				<%= f.submit "Add Friend" %>
        			<% end %>
        		<% end %>

        	<% end %> </li>
        </ul>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="relation_container">
  <div class="relationship_container">
    <div id="user-profile-page">
      <h1> <%= @user.username %> </h1>
      <div class="content_contain">
        <!-- user games list container -->
        <div class="content_list">
          <h1>Game List</h1>
          <ul>
            <% @user.games.each do |game| %>
              <li> <%= link_to game.name, game_path(game) %> </li>
            <% end %>
          </ul>
        </div>
        <div>
          <%= link_to "Find and add new games!", new_library_path %>
        </div>
        <div>
          <!-- delete game here -->
        </div>
        <% if user_signed_in? && @user == current_user %>
        <div>
          <%= link_to "Friends", user_relationships_path(@user) %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>