config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :games do
    post "up"
    post "down"
  end

  resources :tags
  resources :comments do
    post "up"
    post "down"
  end

  resources :users do
    resources :relationships
    get "add_game_to_user_new"
    post "add_game_to_user_create"
  end

  resources :libraries

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'games#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bggapi.rb
class Bggapi < ApplicationRecord
  require 'httparty'

  # def game_description(bggid)
  #   p HTTParty.get("http://www.boardgamegeek.com/xmlapi2/thing?id=#{bggid}&marketplace=1")
  # end

  def hotlist
    return HTTParty.get('http://www.boardgamegeek.com/xmlapi2/hot?boardgame')
  end

  # Not returning search item, need to debug
  def search_title(boardgame)
    return HTTParty.get("http://www.boardgamegeek.com/xmlapi2/search?#{boardgame}")
  end

  def game_title
    data = HTTParty.get('http://www.boardgamegeek.com/xmlapi2/hot?boardgame')
    body = data.parsed_response
    body.each do |key, value|

    all_games = Array.new
    value['item'].first(19).each do |item|
      thumbnail = item['thumbnail']['value']
      name = item['name']['value']
      bggid = item['id']
      des = descriptions(bggid)
      all_games.push(Game.create(bggid: bggid, name: name, thumbnail: "http:#{thumbnail}", description: des))

    end
      return all_games
    end
  end

  def descriptions(bggid)
    descript = Array.new
    descriptions_body = HTTParty.get("http://www.boardgamegeek.com/xmlapi2/thing?id=#{bggid}&marketplace=1")
    p body = descriptions_body.parsed_response
    p "*" * 20
    body.each do |key, value|
    descript.push(value["item"]["description"])
    end
    return descript
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  acts_as_votable

	belongs_to :user
	belongs_to :game

  def tally
    self.get_likes.size - self.get_dislikes.size
  end
end

app/models/game.rb
class Game < ApplicationRecord
  acts_as_votable

	has_many :comments
	has_many :libraries
	has_many :users, through: :libraries
	has_many :gametags
	has_many :tags, through: :gametags

  def tally
    self.get_likes.size - self.get_dislikes.size
  end
end

app/models/gametag.rb
class Gametag < ApplicationRecord
	belongs_to :game
	belongs_to :tag
end

app/models/library.rb
class Library < ApplicationRecord
	belongs_to :user
	belongs_to :game
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :friend, foreign_key: "friend_id", class_name: "User"
	belongs_to :user, foreign_key: "user_id", class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :gametags
	has_many :games, through: :gametags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  has_many :libraries
  has_many :games, through: :libraries
  has_many :comments
  has_many :friends, through: :relationships, source: :friend
  has_many :relationships, foreign_key: :user_id, class_name: "Relationship"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    puts params
    if @comment.save
      # TODO Change redirect_to game show page
      redirect_to(:back)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def up
    comment = Comment.find(params[:comment_id])
    comment.liked_by current_user
    comment.save

    redirect_to(:back)
  end

  def down
    comment = Comment.find(params[:comment_id])
    comment.disliked_by current_user
    comment.save

    redirect_to(:back)
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :user_id, :game_id)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @comment = Comment.new
    @game = Game.find(params[:id])
  end

  #below is only needed for admins
  # def new
  #   @game = Game.new
  # end

  # def create
  #   @game = Game.new(game_params)

  #   if @game.save
  #     redirect_to :action => 'index'
  #   else
  #     render :action => 'new'
  #   end
  # end

  # def edit
  # end

  # def update
  # end

  # def delete
  # end
  def add_game_to_user_new
    # Need to pass games id to this
  end

  def add_game_to_user_create
    # Need to pass games id to this
  end

  def up
    game = Game.find(params[:game_id])
    game.liked_by current_user
    game.save

    redirect_to(:back)
  end

  def down
    game = Game.find(params[:game_id])
    game.disliked_by current_user
    game.save

    redirect_to(:back)
  end

  private
  def game_params
    params.require(:games).permit(:name, :text)
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  def index
    #query current_user and all friends
  end

  def new
  	@games = Game.all
  	@library = Library.new
  end

  def create
	game_id = params[:library][:game_id]
	user_id = current_user.id
	@library = Library.new({:user_id => user_id, :game_id => game_id})
	if @library.save
		redirect_to user_path(current_user)
	end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  # Only for admins
  # def index
  # end

  # def show
  # end

  # def new
  # end

  # def create
  # end

  # def edit
  # end

  # def update
  # end

  # def delete
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  	@relationships = Relationship.all
  	@relationship = Relationship.new
  	if user_signed_in?
  		@user = current_user
  	end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/index.html.erb
<h1 class="title">Board Game Tracker</h1>

<div class="friend_container">
  <%= link_to "Find and add your friends!", users_path %>
</div>

<h3 class="list_title">All Games</h3>
  <div>
    <% @games.each do |game| %>
    	<div class="container">
        <div class="game_list_container">
          <div class="vote_container">
            <%= button_to '', game_up_path(game), {class: 'materials-icons up'} %>
            <p class="vote_counts"><%= game.tally %></p>
            <%= button_to '', game_down_path(game), {class: 'materials-icons down'} %>
          </div>
          <div class="game_content_container">

            <div class="game_image_icon">
              <%= link_to game_path(game) do %>
                <%= image_tag game.thumbnail %>
              <% end %>
            </div>
            <%= link_to game.name, game_path(game) %>
           <p><%=  game.description %></p>


          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/games/show.html.erb
<div class="show_container">
  <h1><%=@game.name%></h1>
  <div class="container">
    <div class="image_icon">
      <%= image_tag @game.thumbnail %>
    </div>
    <div class="comment_container">
      <h1>Comments</h1>
      <div class="add_comment_container">
        <%= form_for @comment do |f| %>
          <%= f.label :content %>
          <%= f.text_area :content %>
          <%= f.hidden_field :user_id, :value => current_user.id %>
          <%= f.hidden_field :game_id, :value => @game.id %>
          <%= f.submit 'Submit', class: 'submit_btn' %>
        <% end %>
      </div>
      <div class="content_container">
          <div class="comment_list_container">
          <% @game.comments.each do |comment| %>
            <div class="each_comment_container">
              <div class="vote_container">
                <%= button_to '', comment_up_path(comment), {class: 'materials-icons up'} %>
                <p class="vote_counts"><%= comment.tally %></p>
                <%= button_to '', comment_down_path(comment), {class: 'materials-icons down'} %>
              </div>

              <% comment_user = User.find(comment.user_id) %>
              <div class="comment_container">
                  <div class="comments">
                    <%= comment.content %> ~ <%= link_to comment_user.username, user_path(comment_user) %>
                  </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/libraries/index.html.erb
<div>
  <!-- libraries container -->
  <div>
    <!-- list container -->
    <div>
      <!-- each library goes here -->
    </div>
  </div>
</div>

app/views/libraries/new.html.erb
<div>
  <% @games.each do |game| %>
  	<div class="container">
      <div class="game_list_container">
        <div class="vote_container">
          <%= button_to '', game_up_path(game), {class: 'materials-icons up'} %>
          <p class="vote_counts"><%= game.tally %></p>
          <%= button_to '', game_down_path(game), {class: 'materials-icons down'} %>
        </div>
        <div class="game_content_container">
          <div>
            <%= link_to game.name, game_path(game) %>
          </div>
          <div class="game_image_icon">
            <%= link_to game_path(game) do %>
              <%= image_tag game.thumbnail %>
            <% end %>
          </div>
        </div>

        <% if user_signed_in? && !current_user.games.include?(game) %>
          <%= form_for(@library, url: libraries_path) do |f| %>
            <%= f.hidden_field :game_id, :value => game.id %>
            <%= f.submit "Add Game" %>
          <% end %>
        <% end %>

      </div>
    </div>
  <% end %>
</div>